[package]
name = "app"
version = "0.1.0"
edition = "2021"


[dependencies]
embedded-hal = "0.2.7"
nb = "1"
cortex-m = { version = "0.7.6", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.3"
# Panic behaviour, see https://crates.io/keywords/panic-impl for alternatives
panic-halt = "0.2.0"
unwrap-infallible = "0.1.5"
stm32f1xx-hal = { version = "0.10", features = ["rt", "stm32f103"] }
rtt-target = "0.4.0"
embedded-alloc = "0.5.0"

rriv-0-4 = { path = "../rriv-0-4" }
rriv-datalogger = { path = "../../src/rriv-datalogger" }
