[workspace]
members = ["app", "lib", "rriv-0-4", "datalogger", "command_service", "rriv_board"]
resolver = "2"

[workspace.package]
authors = ["m. interrupt"]
edition = "2021"
description = "RRIV board packages"
