[workspace]
members = ["control_interface", "command_service", "datalogger"]
resolver = "2"

[workspace.package]
authors = ["m. interrupt"]
edition = "2021"
description = "RRIV rust"
version = "0.0.0"
